// Generated by measure_corpus — DO NOT hand-edit.
// Corpus version: genre-corpus-v2-wiring-v3
//
// Acoustic: 22 curated Bandcamp/Qobuz tracks, gate-v1.1 (retuned
//   from real-corpus measurement — see S-0XX commit history and
//   FINDINGS for full provenance).
//
// IDM: 13 accepted FMA-sourced tracks (16 measured, 3 rejected —
//   see corpus-manifest.json for reasons), gate-v1 UNTUNED —
//   no real-corpus retune pass has happened yet for this bucket.
//   PROVISIONAL: orchestrator is still curating a larger,
//   industry-reference IDM corpus (target ~25 tracks). Re-run
//   measure_corpus and recommit this file when that corpus is
//   ready — do not treat these IDM centroids as final, and do
//   not retune GATE_V1_IDM against this dataset.
//
// Regenerate via: cargo run --release -p m0d --bin measure_corpus
//   <corpus_dir> <out_dir> --corpus-version <tag>

pub const GLOBAL_MFCC_MEAN: [f32; 13] = [
    -11.119668,
    4.584034,
    0.58711207,
    0.7599443,
    0.08857725,
    0.106451094,
    -0.05592127,
    -0.07733158,
    0.0028848147,
    -0.033530764,
    -0.05907082,
    -0.12490638,
    -0.20577186,
];

pub const GLOBAL_MFCC_STD: [f32; 13] = [
    5.3185987, 2.5757036, 1.5194284, 1.0940788, 0.8796425, 0.77144325, 0.69068336, 0.63886774,
    0.5910491, 0.5516147, 0.50830203, 0.49812895, 0.48332223,
];

pub const ACOUSTIC_MFCC_MEAN: [f32; 13] = [
    -0.048787404,
    0.08567484,
    0.031366505,
    0.08613009,
    -0.08388591,
    -0.15681183,
    -0.0953366,
    -0.18672001,
    -0.14418736,
    -0.23260021,
    -0.15560503,
    -0.15888913,
    -0.15584145,
];

pub const IDM_MFCC_MEAN: [f32; 13] = [
    0.0680937,
    -0.119516194,
    -0.04378783,
    -0.12019575,
    0.117067635,
    0.21884108,
    0.13304205,
    0.2605819,
    0.201224,
    0.32460734,
    0.21715866,
    0.2217335,
    0.21748626,
];
