// pre_analysis_contract.rs — Oracle-TDD contract tests for PreAnalysisData
// Authority: Pre-Analysis Constitution v1.3
// Workflow:  Oracle-TDD Step 3 (RED until PreAnalyzer is implemented)
//
// These tests load pre_analysis_reference.json (generated by Python oracle)
// and assert that PreAnalyzer::run() produces matching results.

use lineos_types::pre_analysis::{PreAnalysisData, ZoneActivationFlags};
use serde_json::Value;
use sp314_dsp::analysis::PreAnalyzer;
use std::fs;

// ── Tolerances (approved by constitutional authority) ─────────────────────────

const TOL_CORRELATION: f32 = 1e-6;
const TOL_WIDTH: f32 = 1e-6;
#[allow(dead_code)]
const TOL_LUFS: f32 = 0.3;
#[allow(dead_code)]
const TOL_LRA: f32 = 0.3;
#[allow(dead_code)]
const TOL_DB: f32 = 0.1; // true peak, spectral, crest, side_mid
#[allow(dead_code)]
const TOL_ROLLOFF_HZ: f32 = 50.0;
#[allow(dead_code)]
const TOL_DENSITY: f32 = 0.5;
#[allow(dead_code)]
const TOL_PEAK_HZ: f32 = 5.0;

const SR: u32 = 48000;
const DURATION: f32 = 3.0;

// ── Helpers ──────────────────────────────────────────────────────────────────

fn load_fixture() -> Vec<Value> {
    let path = "tests/fixtures/pre_analysis_reference.json";
    let content = fs::read_to_string(path).unwrap_or_else(|_| panic!("Failed to read {}", path));
    serde_json::from_str(&content).expect("Failed to parse JSON")
}

fn assert_near(name: &str, actual: f32, expected: f32, tol: f32) {
    let diff = (actual - expected).abs();
    assert!(
        diff <= tol,
        "{}: actual={} expected={} diff={} tol={}",
        name,
        actual,
        expected,
        diff,
        tol
    );
}

/// Generate 1000Hz mono sine (L=R), matching Python oracle.
fn gen_sine_1000_mono() -> (Vec<f32>, Vec<f32>) {
    let n = (DURATION * SR as f32) as usize;
    let sig: Vec<f32> = (0..n)
        .map(|i| {
            let t = i as f32 / SR as f32;
            0.5 * libm::sinf(2.0 * core::f32::consts::PI * 1000.0 * t)
        })
        .collect();
    (sig.clone(), sig)
}

/// Generate white noise (decorrelated L≠R), seed=42.
/// Uses xorshift32 for determinism (no rand crate).
#[allow(dead_code)]
fn gen_white_noise_decorrelated() -> (Vec<f32>, Vec<f32>) {
    let n = (DURATION * SR as f32) as usize;
    // We only need this for the deterministic_100 test.
    // Use a simple PRNG matching the Python oracle's seed=42 output
    // is not required here — the contract test compares PreAnalyzer
    // output against itself for determinism, not against Python.
    let mut state_l: u32 = 42;
    let mut state_r: u32 = 12345;
    let mut left = Vec::with_capacity(n);
    let mut right = Vec::with_capacity(n);
    for _ in 0..n {
        state_l ^= state_l << 13;
        state_l ^= state_l >> 17;
        state_l ^= state_l << 5;
        state_r ^= state_r << 13;
        state_r ^= state_r >> 17;
        state_r ^= state_r << 5;
        left.push((state_l as f32 / u32::MAX as f32 - 0.5) * 0.6);
        right.push((state_r as f32 / u32::MAX as f32 - 0.5) * 0.6);
    }
    (left, right)
}

/// Generate problem mix matching Python oracle construction.
fn gen_problem_mix() -> (Vec<f32>, Vec<f32>) {
    let n = (DURATION * SR as f32) as usize;
    let pi2 = 2.0 * core::f32::consts::PI;
    let mut left = vec![0.0f32; n];
    let mut right = vec![0.0f32; n];

    // Use xorshift for deterministic noise (seed=99 equivalent)
    let mut rng_l: u32 = 99;
    let mut rng_r: u32 = 999;

    // Frequencies for harsh cluster with phase offsets
    // (simplified — exact phase match to Python not required for zone flag tests)
    let harsh_freqs = [
        2500.0f32, 3000.0, 3500.0, 4000.0, 4500.0, 5000.0, 5500.0, 6000.0,
    ];

    for i in 0..n {
        let t = i as f32 / SR as f32;
        let sub = 0.7 * libm::sinf(pi2 * 60.0 * t);
        let box_ = 0.7 * libm::sinf(pi2 * 350.0 * t) + 0.3 * libm::sinf(pi2 * 400.0 * t);
        let mut harsh = 0.0f32;
        for &freq in &harsh_freqs {
            harsh += 0.2 * libm::sinf(pi2 * freq * t);
        }

        rng_l ^= rng_l << 13;
        rng_l ^= rng_l >> 17;
        rng_l ^= rng_l << 5;
        rng_r ^= rng_r << 13;
        rng_r ^= rng_r >> 17;
        rng_r ^= rng_r << 5;
        let nl = (rng_l as f32 / u32::MAX as f32 - 0.5) * 0.8;
        let nr = (rng_r as f32 / u32::MAX as f32 - 0.5) * 0.8;

        let l = sub + box_ + harsh + nl;
        let r = -sub * 0.5 + box_ * 0.3 + harsh * 0.6 + nr;

        left[i] = l.clamp(-0.9, 0.9);
        right[i] = r.clamp(-0.9, 0.9);
    }
    (left, right)
}

// ── Test 1: Serde roundtrip ──────────────────────────────────────────────────

#[test]
fn serde_roundtrip() {
    let fixtures = load_fixture();
    assert_eq!(fixtures.len(), 3, "Expected 3 test cases in fixture");

    for case in &fixtures {
        // Deserialize into PreAnalysisData
        let data: PreAnalysisData = serde_json::from_value(strip_meta(case.clone()))
            .expect("Failed to deserialize PreAnalysisData");

        // Re-serialize
        let json = serde_json::to_value(&data).expect("Failed to serialize");

        // Deserialize again
        let data2: PreAnalysisData =
            serde_json::from_value(json).expect("Failed to re-deserialize");

        assert_eq!(
            data,
            data2,
            "Serde roundtrip failed for {}",
            case["signal_id"].as_str().unwrap_or("unknown")
        );
    }
}

/// Strip non-PreAnalysisData fields (signal_id, tolerances, etc.)
fn strip_meta(mut v: Value) -> Value {
    if let Some(obj) = v.as_object_mut() {
        obj.remove("signal_id");
        obj.remove("tolerances");
        obj.remove("sample_rate");
        obj.remove("duration_ms");
        obj.remove("channel_count");
        // Add rhythm fields since Python oracle doesn't generate them
        if !obj.contains_key("bpm") {
            obj.insert("bpm".to_string(), serde_json::json!(0.0));
            obj.insert("beats_ms".to_string(), serde_json::json!(Vec::<u32>::new()));
            obj.insert(
                "downbeats_ms".to_string(),
                serde_json::json!(Vec::<u32>::new()),
            );
            obj.insert(
                "transients_ms".to_string(),
                serde_json::json!(Vec::<u32>::new()),
            );
        }
    }
    v
}

// ── Test 2: Sine 1000Hz semantics ────────────────────────────────────────────

#[test]
fn sine_1000_semantics() {
    let (left, right) = gen_sine_1000_mono();
    let result = PreAnalyzer::run(&left, &right, SR);

    assert_near(
        "correlation",
        result.global_phase_correlation,
        1.0,
        TOL_CORRELATION,
    );
    assert!(
        result.transient_density < 0.5,
        "Sine should have near-zero transient density, got {}",
        result.transient_density
    );
    assert_near("stereo_width", result.stereo_width, 0.0, TOL_WIDTH);

    // All zone flags must be false for a clean sine
    assert!(
        !result.zone_flags.zone_cymbal_harsh,
        "sine: cymbal_harsh should be false"
    );
    assert!(
        !result.zone_flags.zone_sub_rumble,
        "sine: sub_rumble should be false"
    );
    assert!(
        !result.zone_flags.zone_boxiness,
        "sine: boxiness should be false"
    );
    assert!(
        !result.zone_flags.zone_phase_issue,
        "sine: phase_issue should be false"
    );
    assert!(
        !result.zone_flags.zone_harsh_resonance,
        "sine: harsh_resonance should be false"
    );
}

// ── Test 3: Zone flags on problem mix ────────────────────────────────────────

#[test]
fn zone_flags_problem_mix() {
    let (left, right) = gen_problem_mix();
    let result = PreAnalyzer::run(&left, &right, SR);

    // These 3 must be true (per fixture)
    assert!(
        result.zone_flags.zone_sub_rumble,
        "problem_mix: sub_rumble should be true"
    );
    assert!(
        result.zone_flags.zone_boxiness,
        "problem_mix: boxiness should be true"
    );
    assert!(
        result.zone_flags.zone_phase_issue,
        "problem_mix: phase_issue should be true"
    );

    // Load fixture to compare all 5 flags exactly
    let fixtures = load_fixture();
    let fixture_flags = &fixtures[2]["zone_flags"];
    assert_eq!(
        result.zone_flags.zone_cymbal_harsh,
        fixture_flags["zone_cymbal_harsh"].as_bool().unwrap(),
        "cymbal_harsh mismatch"
    );
    assert_eq!(
        result.zone_flags.zone_harsh_resonance,
        fixture_flags["zone_harsh_resonance"].as_bool().unwrap(),
        "harsh_resonance mismatch"
    );
}

// ── Test 4: Deterministic 100 runs ───────────────────────────────────────────

#[test]
fn deterministic_100_runs() {
    let (left, right) = gen_sine_1000_mono();
    let baseline = PreAnalyzer::run(&left, &right, SR);

    for run in 1..100 {
        let result = PreAnalyzer::run(&left, &right, SR);
        assert_eq!(
            result.integrated_lufs, baseline.integrated_lufs,
            "LUFS not bit-identical on run {}",
            run
        );
        assert_eq!(
            result.global_phase_correlation, baseline.global_phase_correlation,
            "Correlation not bit-identical on run {}",
            run
        );
        assert_eq!(
            result.spectral_profile_db, baseline.spectral_profile_db,
            "Spectral profile not bit-identical on run {}",
            run
        );
        assert_eq!(
            result.resonant_peaks_hz, baseline.resonant_peaks_hz,
            "Resonant peaks not bit-identical on run {}",
            run
        );
    }
}

// ── Test 5: Resonant peaks invariants ────────────────────────────────────────

#[test]
fn resonant_peaks_invariants() {
    let fixtures = load_fixture();
    for case in &fixtures {
        let peaks: Vec<f64> = case["resonant_peaks_hz"]
            .as_array()
            .unwrap()
            .iter()
            .map(|v| v.as_f64().unwrap())
            .collect();

        let sid = case["signal_id"].as_str().unwrap();

        assert!(
            peaks.len() <= 16,
            "{}: too many peaks ({}), max 16",
            sid,
            peaks.len()
        );

        for (i, &p) in peaks.iter().enumerate() {
            assert!(p > 0.0, "{}: peak[{}] = {} is not positive", sid, i, p);
            if i > 0 {
                assert!(
                    p >= peaks[i - 1],
                    "{}: peaks not sorted ascending: [{}]={} < [{}]={}",
                    sid,
                    i - 1,
                    peaks[i - 1],
                    i,
                    p
                );
            }
        }
    }
}

// ── Test 6: Resonant peaks vs fixture ────────────────────────────────────────
// Note: Rust problem_mix uses xorshift RNG, Python uses numpy.random.
// Exact peak counts won't match. We verify structural invariants instead.

#[test]
fn resonant_peaks_vs_fixture() {
    let (left, right) = gen_problem_mix();
    let result = PreAnalyzer::run(&left, &right, SR);

    // Must have peaks (the harsh cluster at 2.5k-6kHz guarantees this)
    assert!(
        !result.resonant_peaks_hz.is_empty(),
        "problem_mix should produce resonant peaks"
    );

    // All peaks must be capped at 16
    assert!(
        result.resonant_peaks_hz.len() <= 16,
        "Peaks should be capped at 16, got {}",
        result.resonant_peaks_hz.len()
    );

    // All peaks must be sorted ascending and >10Hz apart (thinning)
    for i in 1..result.resonant_peaks_hz.len() {
        assert!(
            result.resonant_peaks_hz[i] > result.resonant_peaks_hz[i - 1],
            "Peaks not sorted at index {}",
            i
        );
        assert!(
            result.resonant_peaks_hz[i] - result.resonant_peaks_hz[i - 1] > 10.0,
            "Peaks not thinned at index {}: {} and {}",
            i,
            result.resonant_peaks_hz[i - 1],
            result.resonant_peaks_hz[i]
        );
    }

    // Most peaks should be in the 2k-8k HighMid band (the harsh cluster)
    let highmid_count = result
        .resonant_peaks_hz
        .iter()
        .filter(|&&f| (2000.0..=8000.0).contains(&f))
        .count();
    assert!(
        highmid_count > 0,
        "problem_mix should have peaks in HighMid (2k-8kHz), got 0"
    );
}

// ── Test 7: Band correlation in range ────────────────────────────────────────

#[test]
fn band_correlation_in_range() {
    let fixtures = load_fixture();
    for case in &fixtures {
        let bpc: Vec<f64> = case["band_phase_correlation"]
            .as_array()
            .unwrap()
            .iter()
            .map(|v| v.as_f64().unwrap())
            .collect();

        let sid = case["signal_id"].as_str().unwrap();
        assert_eq!(bpc.len(), 8, "{}: expected 8 band correlations", sid);

        for (i, &c) in bpc.iter().enumerate() {
            assert!(
                (-1.0..=1.0).contains(&c),
                "{}: band_phase_correlation[{}] = {} out of range [-1,1]",
                sid,
                i,
                c
            );
        }
    }
}

// ── Test 8: Empty input returns silent ───────────────────────────────────────

#[test]
fn empty_input_silent() {
    let result = PreAnalyzer::run(&[], &[], 44100);
    let silent = PreAnalysisData::silent();

    assert_eq!(result.integrated_lufs, silent.integrated_lufs);
    assert_eq!(result.true_peak_dbtp, silent.true_peak_dbtp);
    assert_eq!(
        result.global_phase_correlation,
        silent.global_phase_correlation
    );
    assert_eq!(result.stereo_width, silent.stereo_width);
    assert_eq!(result.side_mid_ratio_db, silent.side_mid_ratio_db);
    assert_eq!(result.spectral_profile_db, silent.spectral_profile_db);
    assert_eq!(result.band_phase_correlation, silent.band_phase_correlation);
    assert!(
        result.resonant_peaks_hz.is_empty(),
        "Empty input should have no peaks"
    );
    assert_eq!(result.zone_flags, ZoneActivationFlags::default());
}

// ── Test 9: Short input returns safe defaults ────────────────────────────────

#[test]
fn short_input_silent() {
    let short = vec![0.1f32; 1000];
    let result = PreAnalyzer::run(&short, &short, 44100);

    // Must not panic. All zone flags must be false.
    assert!(!result.zone_flags.zone_cymbal_harsh);
    assert!(!result.zone_flags.zone_sub_rumble);
    assert!(!result.zone_flags.zone_boxiness);
    assert!(!result.zone_flags.zone_phase_issue);
    assert!(!result.zone_flags.zone_harsh_resonance);

    // No NaN or Inf in any field
    assert!(result.integrated_lufs.is_finite(), "LUFS is not finite");
    assert!(result.true_peak_dbtp.is_finite(), "True peak is not finite");
    assert!(
        result.global_phase_correlation.is_finite(),
        "Correlation is not finite"
    );
    assert!(result.stereo_width.is_finite(), "Width is not finite");
    for (i, &v) in result.spectral_profile_db.iter().enumerate() {
        assert!(v.is_finite(), "spectral_profile_db[{}] is not finite", i);
    }
    for (i, &v) in result.band_phase_correlation.iter().enumerate() {
        assert!(v.is_finite(), "band_phase_correlation[{}] is not finite", i);
    }
}

// ── Test 10: Spectral Profile Wrapper ────────────────────────────────────────

#[test]
fn spectral_profile_levels_wrapper() {
    let sr = 48000;
    let n = sr; // 1 second
    let pi2 = 2.0 * core::f32::consts::PI;

    // Sine at 150Hz (Band 1: 80-250) and 1500Hz (Band 4: 1k-2k)
    let left: Vec<f32> = (0..n)
        .map(|i| {
            let t = i as f32 / sr as f32;
            0.5 * libm::sinf(pi2 * 150.0 * t) + 0.5 * libm::sinf(pi2 * 1500.0 * t)
        })
        .collect();
    let right = left.clone();

    // 1. Call the public wrapper
    let levels = sp314_dsp::analysis::spectral_profile_levels(&left, &right, sr);

    // 2. Call the production PreAnalyzer to get the internal 8-band result
    let result = PreAnalyzer::run(&left, &right, sr);

    // 3. Assert bit-exact identity
    for k in 0..8 {
        assert_eq!(
            levels[k].to_bits(),
            result.spectral_profile_db[k].to_bits(),
            "Band {} mismatch",
            k
        );
    }

    // 4. Sanity-assert the band containing each sine is the loudest of its neighborhood
    // Band 1 (150Hz) should be > Band 0 (20-80) and Band 2 (250-500)
    assert!(levels[1] > levels[0], "Band 1 should be > Band 0");
    assert!(levels[1] > levels[2], "Band 1 should be > Band 2");

    // Band 4 (1500Hz) should be > Band 3 (500-1k) and Band 5 (2k-4k)
    assert!(levels[4] > levels[3], "Band 4 should be > Band 3");
    assert!(levels[4] > levels[5], "Band 4 should be > Band 5");
}

// ── Test 11: Spectral Slope ──────────────────────────────────────────────────

#[test]
fn spectral_slope_contract() {
    let band_edges: [f32; 9] = [
        20.0, 80.0, 250.0, 500.0, 1000.0, 2000.0, 4000.0, 8000.0, 20000.0,
    ];
    let mut centers = [0.0; 8];
    for k in 0..8 {
        centers[k] = libm::sqrtf(band_edges[k] * band_edges[k + 1]);
    }

    // a) synthetic -1.0 fixture: levels_db[k] = -20*log10(center_k / center_1) for k in 1..=6
    // NOTE: Because spectral_slope now normalizes by bandwidth density (subtracting 10*log10(BW)),
    // and our bandwidths roughly double per octave (proportional to center_k), the bandwidth term
    // adds a slope of approximately -0.5. Thus, an amplitude slope of -1.0 minus the bandwidth
    // term (-0.5) yields an expected reading of ≈ -1.5.
    let mut fixture_minus_one = [0.0; 8];
    fixture_minus_one[0] = 99.0; // arbitrary junk
    fixture_minus_one[7] = -99.0; // arbitrary junk
    for k in 1..=6 {
        fixture_minus_one[k] = -20.0 * libm::log10f(centers[k] / centers[1]);
    }
    let slope1 = sp314_dsp::analysis::spectral_slope(&fixture_minus_one);
    assert!(
        libm::fabsf(slope1 - (-1.5)) < 0.2,
        "Expected slope ~ -1.5, got {}",
        slope1
    );

    // b) flat spectrum -> slope 0.0 (now ~ -0.5 due to density)
    let flat_spectrum = [-12.0; 8];
    let slope2 = sp314_dsp::analysis::spectral_slope(&flat_spectrum);
    assert!(
        libm::fabsf(slope2 - (-0.5)) < 0.2,
        "Expected slope ~ -0.5, got {}",
        slope2
    );

    // c) band-exclusion proof: two inputs identical in bands 1..=6 but wildly different in bands 0 and 7
    let mut different_ends = fixture_minus_one;
    different_ends[0] = -144.0;
    different_ends[7] = 20.0;
    let slope3 = sp314_dsp::analysis::spectral_slope(&different_ends);
    assert_eq!(
        slope1.to_bits(),
        slope3.to_bits(),
        "Slope should be bit-identical regardless of bands 0 and 7"
    );

    // d) positive tilt fixture (+ slope) -> sign is positive
    let mut positive_tilt = [0.0; 8];
    for k in 1..=6 {
        positive_tilt[k] = 20.0 * libm::log10f(centers[k] / centers[1]);
    }
    let slope4 = sp314_dsp::analysis::spectral_slope(&positive_tilt);
    assert!(slope4 > 0.0, "Expected positive slope, got {}", slope4);
}

// ── Test: Broadband spectral slope density ────────────────────────────────────

#[test]
fn spectral_slope_broadband_density() {
    let sr = 48000;
    let n = sr * 2; // 2 seconds
    let pi2 = 2.0 * core::f32::consts::PI;

    // Build dense comb log-spaced every 1/24 octave from 100Hz to 10kHz
    let mut freqs = Vec::new();
    let mut f = 100.0f32;
    let multiplier = libm::powf(2.0, 1.0 / 24.0);
    while f <= 10000.0 {
        freqs.push(f);
        f *= multiplier;
    }

    let test_slope = |s: f32| {
        let mut left = vec![0.0f32; n];
        for &freq in &freqs {
            // NOTE: Since the comb is log-spaced, the density of sines is 1/f.
            // To achieve a power spectral density (PSD) proportional to f^{2s},
            // the energy per sine must be f^{2s + 1}. Thus, amplitude is f^{s + 0.5}.
            // This ensures a pink-like comb (s=-0.5) has constant amplitude (PSD \propto 1/f),
            // which reads ≈ 0 without density correction, and -0.5 with it.
            let amp = libm::powf(freq, s + 0.5);
            for i in 0..n {
                let t = i as f32 / sr as f32;
                left[i] += amp * libm::sinf(pi2 * freq * t);
            }
        }
        let max_val = left
            .iter()
            .map(|v| libm::fabsf(*v))
            .fold(0.0f32, |a, b| a.max(b));
        if max_val > 0.0 {
            for v in left.iter_mut() {
                *v = (*v / max_val) * 0.5;
            }
        }

        let right = left.clone();
        let levels = sp314_dsp::analysis::spectral_profile_levels(&left, &right, sr as u32);
        sp314_dsp::analysis::spectral_slope(&levels)
    };

    let slope_minus_half = test_slope(-0.5);
    let slope_minus_one = test_slope(-1.0);

    println!("SLOPE MINUS HALF: {}", slope_minus_half);
    println!("SLOPE MINUS ONE: {}", slope_minus_one);

    // Tolerance ±0.15: F-030 — Butterworth skirt leakage biases
    // slope readings ~0.1 shallow even on dense combs. The test's
    // discriminating power is intact: the pre-fix bug read ≈ 0
    // (error 0.5), far outside this window.
    assert!(
        libm::fabsf(slope_minus_half - (-0.5)) <= 0.15,
        "Expected slope -0.5, got {}",
        slope_minus_half
    );
    assert!(
        libm::fabsf(slope_minus_one - (-1.0)) <= 0.15,
        "Expected slope -1.0, got {}",
        slope_minus_one
    );
    assert!(
        slope_minus_half < -0.3,
        "Bug-catching: pre-fix ≈ 0 cannot pass this"
    );
    assert!(
        slope_minus_one < -0.6,
        "Bug-catching: pre-fix ≈ 0 cannot pass this"
    );
}

// ── Test 12: LRA Contract ────────────────────────────────────────────────────

#[test]
fn loudness_range_contract() {
    let sr = 48000;
    // 3s sine at 0.5 amplitude followed by 3s at 0.05
    let total_samples = sr * 6;
    let mut fixture = Vec::with_capacity(total_samples);
    let freq = 1000.0;
    let two_pi = 2.0 * core::f32::consts::PI;

    for i in 0..total_samples {
        let t = i as f32 / sr as f32;
        let amp = if t < 3.0 { 0.5 } else { 0.05 };
        fixture.push(amp * libm::sinf(two_pi * freq * t));
    }

    let lra_wrapper = sp314_dsp::analysis::loudness_range_lu(&fixture, &fixture);

    let data = sp314_dsp::analysis::PreAnalyzer::run(&fixture, &fixture, sr as u32);

    assert_eq!(
        lra_wrapper.to_bits(),
        data.loudness_range.to_bits(),
        "LRA wrapper must be bit-identical to PreAnalyzer::run"
    );

    assert!(lra_wrapper > 0.0, "LRA must be > 0.0");
    assert!(lra_wrapper.is_finite(), "LRA must be finite");
}

// ── Test 14: Genre Classification ────────────────────────────────────────────

#[test]
fn test_pre_analyzer_populates_genre() {
    // 20s excerpt from BoDleasons - Our Journey.mp3 (middle of track, avoiding
    // sparse intro), a gate-accepted IDM corpus track — see S-0XX corpus-manifest.json
    // for full provenance.
    let path = "tests/fixtures/bodleasons_mid.wav";
    let mut reader = hound::WavReader::open(path).expect("Failed to open fixture");
    let spec = reader.spec();

    let mut left = Vec::new();
    let mut right = Vec::new();
    // Use the 16-bit integer conversion since real_world_60s.wav is 16-bit PCM.
    let samples: Vec<i32> = reader.samples().map(|s| s.unwrap()).collect();

    for chunk in samples.chunks(2) {
        // Convert to f32 PCM [-1.0, 1.0]
        left.push(chunk[0] as f32 / 32768.0);
        right.push(chunk[1] as f32 / 32768.0);
    }

    let data = PreAnalyzer::run(&left, &right, spec.sample_rate);

    println!("Genre for bodleasons_mid: {:?}", data.genre);
    assert_eq!(
        data.genre,
        Some(lineos_types::pre_analysis::Genre::Idm),
        "bodleasons mid must resolve to Idm"
    );

    // Silence/short input case
    let silent_data = PreAnalyzer::run(&[0.0; 100], &[0.0; 100], 48000);
    assert_eq!(
        silent_data.genre, None,
        "Short/silent input should yield None genre"
    );
}
