import json
import glob
import numpy as np
import os

# INV-CP-1: Deterministic random seed
np.random.seed(42)

STATES = ["silence", "breath", "consonant", "vowel", "tail"]
NUM_STATES = len(STATES)
state_to_idx = {s: i for i, s in enumerate(STATES)}

counts = np.zeros((NUM_STATES, NUM_STATES), dtype=int)

# Read all existing corpus files
for fpath in glob.glob("session_*.corpus.json"):
    try:
        with open(fpath, "r") as f:
            data = json.load(f)
    except Exception:
        continue
        
    for stem_data in data.get("stems", []):
        if stem_data.get("stem_type") == "voice":
            events = stem_data.get("events", [])
            # Sort by start_ms to ensure chronological order
            events = sorted(events, key=lambda x: x.get("start_ms", 0))
            
            for i in range(len(events) - 1):
                ev1 = events[i]
                ev2 = events[i+1]
                # INV-CP-9: session_id guard in transition counter
                if ev1.get("session_id") == ev2.get("session_id"):
                    s1 = ev1.get("state")
                    s2 = ev2.get("state")
                    if s1 in state_to_idx and s2 in state_to_idx:
                        counts[state_to_idx[s1], state_to_idx[s2]] += 1

matrix = np.zeros((NUM_STATES, NUM_STATES), dtype=float)

def largest_remainder_round(probs, decimals=2):
    # INV-CP-10: Largest remainder correction on rounding
    factor = 10 ** decimals
    scaled = probs * factor
    floored = np.floor(scaled)
    remainders = scaled - floored
    
    diff = int(round(factor - np.sum(floored)))
    
    # Sort indices by remainder in descending order
    indices = np.argsort(remainders)[::-1]
    
    for i in range(diff):
        floored[indices[i]] += 1
        
    return floored / factor

for i in range(NUM_STATES):
    row_sum = np.sum(counts[i])
    if row_sum == 0:
        # INV-CP-8: Zero-frequency -> uniform fallback (never NaN)
        row_probs = np.ones(NUM_STATES) / NUM_STATES
    else:
        row_probs = counts[i] / row_sum
        
    matrix[i] = largest_remainder_round(row_probs, 2)

# Generate Rust code
rust_code = f"""// AUTO-GENERATED BY tools/corpus/run_pipeline.py
// INV-CP-1: Seed fixed (42)
// INV-CP-8: Zero-frequency uniform fallback
// INV-CP-9: Session boundary guarded
// INV-CP-10: Largest remainder correction
use crate::markov::voice_v1::VoiceState;

pub const TRANSITION_MATRIX_VOICE_V2: [[f32; 5]; 5] = [
"""

for i in range(NUM_STATES):
    row_str = ", ".join([f"{v:.2f}" for v in matrix[i]])
    rust_code += f"    [{row_str}],\n"

rust_code += "];\n"

os.makedirs("aether/markov/generated", exist_ok=True)
with open("aether/markov/generated/generated_voice_v2.rs", "w") as f:
    f.write(rust_code)

print("Generated aether/markov/generated/generated_voice_v2.rs")
