import numpy as np
from pathlib import Path

def main():
    mel_basis = np.frombuffer(Path("outputs/mel_basis.bin").read_bytes(), dtype='<f8').reshape(24, 1025)
    
    rust_code = [
        "// Automatically generated by research/superflux/generate_rust_weights.py",
        "// Clean-room port: derived from librosa.filters.mel(sr=48000, n_fft=2048, n_mels=24)",
        "// Citation: Böck & Widmer 2013 (SuperFlux), filterbank configuration.",
        "",
        "pub const MEL_BANDS: usize = 24;",
        "",
        "pub struct MelBand {",
        "    pub start_bin: usize,",
        "    pub weights: &'static [f32],",
        "}",
        "",
        "pub static MEL_BASIS: [MelBand; MEL_BANDS] = ["
    ]
    
    for i in range(24):
        band = mel_basis[i]
        nonzeros = np.where(band > 0)[0]
        if len(nonzeros) > 0:
            start_bin = nonzeros[0]
            end_bin = nonzeros[-1]
            weights = band[start_bin:end_bin+1]
        else:
            start_bin = 0
            weights = np.array([])
            
        weights_str = ", ".join(f"{w:.6E}_f32" for w in weights)
        
        rust_code.append("    MelBand {")
        rust_code.append(f"        start_bin: {start_bin},")
        rust_code.append(f"        weights: &[{weights_str}],")
        rust_code.append("    },")
        
    rust_code.append("];")
    
    out_path = Path("../../lineos/m1/sp314-dsp/src/analysis/superflux_weights.rs")
    out_path.write_text("\n".join(rust_code))

if __name__ == "__main__":
    main()
